import time
song='''I heard you on my wireless back in '52,
Lying awake, intent at tuning in on you,
If I was young, it didn't stop you coming through,
Oh-a, oh-a,
They took the credit for your second symphony,
Rewritten by machine and new technology,
And now I understand the problems you can see,
Oh-a oh-a,
I met your children,
Oh-a oh-a,
What did you tell them?,
Video killed the radio star,
Video killed the radio star,
Pictures came and broke your heart,
Oh-a-a-a oh,
And now we meet in an abandoned studio,
We hear the playback and it seems so long ago,
And you remember the jingles used to go,
Oh-a oh-a,
You were the first one,
Oh-a oh-a,
You are the last one,
Video killed the radio star,
Video killed the radio star,
In my mind and in my car,
We can't rewind, we've gone too far,
Oh-a-aho oh,
Oh-a-aho oh,
Video killed the radio star,
Video killed the radio star,
In my mind and in my car,
We can't rewind, we've gone too far,
Pictures came and broke your heart,
Put the blame on VCR,
You are a radio star,
You are a radio star,
Video killed the radio star,
Video killed the radio star,
'''
song_split1=song.split(",")
for i in range(len(song_split1)):
    print(song_split1[i])
    time.sleep(1)
